### GET
GET localhost:8080/public
Content-Type: */*

###
GET localhost:8080/public/2
Content-Type: */*

### GET
GET localhost:8080/forbidden
Content-Type: */*

###
GET localhost:8080/forbidden/
Content-Type: */*

### GET
GET localhost:8080/roles-secured
Content-Type: */*

###
GET localhost:8080/roles-secured/2
Content-Type: */*

### GET
GET localhost:8080/other
Content-Type: */*

###
GET localhost:8080/other/2
Content-Type: */*
