# 1. Emitters (`Emitter`) + `@Channel`
## 1.1 allows, | imperative code, send messages -- to a -- specific channel
###
POST localhost:8080/send
Content-Type: application/json

42.5

###
POST localhost:8080/sendmutiny
Content-Type: application/json

22.5

### 1.2 `Emitter`
### 1.2.1 allows: buffering (== if there are NO consumers -> keep the messages) messages / sent to the channel
#### 1.2.1.1 send 1!
POST localhost:8080/buffer/send
Content-Type: text/plain

"Message 1"

#### 1.2.1.1 send MULTIPLE
POST localhost:8080/buffer/sendMultiple
Content-Type: text/plain

### 1.2.2 vs Mutiny APIs: Mutiny has MORE control
#### 1.2.2.1 Emitter
POST localhost:8080/control/regular?msg=regularAlfred

#### 1.2.2.2 MutinyEmitter
#### 1.2.2.2.1 MORE control
#### 1.2.2.2.1.1 async
#### 1.2.2.2.1.1.1 valid
POST localhost:8080/control/mutiny-async?msg=multiAsyncAlfred
#### 1.2.2.2.1.1.2 invalid
POST localhost:8080/control/mutiny-async?msg=fail
#### 1.2.2.2.1.2 sync
#### 1.2.2.2.1.2.1 valid
POST localhost:8080/control/mutiny-blocking?msg=multiSyncAlfred
#### 1.2.2.2.1.2.2 invalid
POST localhost:8080/control/mutiny-blocking?msg=fail

## 1.3 | consume messages / sent -- via -- `@Channel` -> application code is responsible for subscribing | stream
### 1.3.1 == MANUAL subscription
GET localhost:8080/subscription/manual

