////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Configuring Your Application
include::_attributes.adoc[]
:categories: core
:summary: Hardcoded values in your code is a no go (even if we all did it at some point ;-)). In this guide, we learn how to configure your application.
:topics: configuration

* goal
    ** how to configure a Quarkus application

* allows
    ** | your code,
        *** ❌NOT hardcode value❌

== Prerequisites

include::{includes}/prerequisites.adoc[]

== Solution

* link:{quickstarts-tree-url}/config-quickstart[here]

== Create the Maven project

WAYS

:create-app-artifact-id: config-quickstart
:create-app-extensions: rest
include::{includes}/devtools/create-app.adoc[]

== Create the configuration

* Quarkus application configuration
    ** 👀-- based on -- https://github.com/smallrye/smallrye-config[SmallRye Config API]👀
    ** reads -- from -- <<config-reference.adoc#configuration-sources,MULTIPLE sources>>

== Inject the configuration

* Quarkus
    ** inject configuration properties | application -- via --
        *** 💡https://microprofile.io/project/eclipse/microprofile-config[MicroProfile Config] annotations💡
            **** ways
                ***** `@ConfigProperty` OR
                ***** `@Inject @ConfigProperty`
                    ****** ❌`@Inject` NOT necessary❌
            **** ⚠️if the application tries to inject a configuration property / NOT set -> throws an error⚠️
        *** if you want to group >1 configurations | 1! interface -> use https://smallrye.io/smallrye-config/Main/config/mappings/[`@io.smallrye.config.ConfigMapping`]

[[secrets-in-environment-properties]]
== Store secrets in an environment properties file

A secret (such as a password, a personal access token or an API key) must not end up in version control
for security reasons. One way is to store them in a local environment properties (`.env`) file:

. Store the secret in the `.env` file in the project root directory.
+
.The .env file
[source,properties]
----
foo.api-key=ThisIsSecret
----

. Add the `.env` file to `.gitignore`.

`mvn quarkus:dev` automatically picks up the properties in the `.env` file,
similar to those in the `application.properties` file.

== Update the test

We also need to update the functional test to reflect the changes made to the endpoint.
Create the `src/test/java/org/acme/config/GreetingResourceTest.java` file with the following content:

[source,java]
----
package org.acme.config;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

@QuarkusTest
public class GreetingResourceTest {

    @Test
    public void testHelloEndpoint() {
        given()
          .when().get("/greeting")
          .then()
             .statusCode(200)
             .body(is("hello quarkus!")); // Modified line
    }

}
----

== Package and run the application

include::{includes}/devtools/dev.adoc[]

* 👀if you change the configuration file -> IMMEDIATELY reflected WITHOUT shut down👀

include::{includes}/devtools/build.adoc[]

include::{includes}/devtools/build-native.adoc[]

== Programmatically access the configuration

The `org.eclipse.microprofile.config.ConfigProvider.getConfig()` API allows to access the Config API programmatically.
This API is mostly useful in situations where CDI injection is not available.

[source,java]
----
String databaseName = ConfigProvider.getConfig().getValue("database.name", String.class);
Optional<String> maybeDatabaseName = ConfigProvider.getConfig().getOptionalValue("database.name", String.class);
----

== Configuring Quarkus

Quarkus itself is configured via the same mechanism as your application. Quarkus reserves the `quarkus.` namespace
for its own configuration. For example to configure the HTTP server port you can set `quarkus.http.port` in
`application.properties`. All the Quarkus configuration properties are xref:all-config.adoc[documented and searchable].

[IMPORTANT]
====
As mentioned above, properties prefixed with `quarkus.` are effectively reserved for configuring Quarkus itself and its
extensions. Therefore, the `quarkus.` prefix should **never** be used for application specific properties.
====

=== Build Time configuration

Some Quarkus configurations only take effect during build time, meaning is not possible to change them at runtime. These
configurations are still available at runtime but as read-only and have no effect in Quarkus behaviour. A change to any
of these configurations requires a rebuild of the application itself to reflect changes of such properties.

TIP: The properties fixed at build time are marked with a lock icon (icon:lock[]) in the xref:all-config.adoc[list of all configuration options].

However, some extensions do define properties _overridable at runtime_. A simple example is the database URL, username
and password which is only known specifically in your target environment, so they can be set and influence the
application behaviour at runtime.

[[additional-information]]
== Additional Information

* xref:config-reference.adoc[Configuration Reference Guide]
* xref:config-yaml.adoc[YAML ConfigSource Extension]
* https://github.com/quarkiverse/quarkus-vault[HashiCorp Vault ConfigSource Extension]
* https://github.com/quarkiverse/quarkus-config-extensions[Consul ConfigSource Extension]
* xref:spring-cloud-config-client.adoc[Spring Cloud ConfigSource Extension]
* xref:config-mappings.adoc[Mapping configuration to objects]
* xref:config-extending-support.adoc[Extending configuration support]

Quarkus relies on link:https://github.com/smallrye/smallrye-config/[SmallRye Config] and inherits its features:

* Additional ``ConfigSource``s
* Additional ``Converter``s
* Indexed properties
* Parent profile
* Interceptors for configuration value resolution
* Relocate configuration properties
* Fallback configuration properties
* Logging
* Hide secrets

For more information, please check the
link:https://smallrye.io/smallrye-config/Main/[SmallRye Config documentation].
