////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Continuous Testing
include::_attributes.adoc[]
:categories: core
:summary: Get early test feedback with Continuous Testing.
:numbered:
:sectnums:
:sectnumlevels: 4
:topics: testing,dev-ui,tooling,dev-mode

* goal
    ** how to use continuous testing | your Quarkus Application

== Prerequisites

include::{includes}/prerequisites.adoc[]
* xref:getting-started.adoc[Getting Started Guide]

== Introduction

* continuous testing
    ** allows
        *** ðŸ‘€if code changes ->
            **** run ONLY RELATED testsðŸ‘€
                ***** Reason: ðŸ§ Quarkus -- detects -- code / EACH testðŸ§ 
            **** get instant feedback ðŸ‘€

== Solution

* xref:getting-started.adoc[Getting Started]

include::{includes}/devtools/dev.adoc[]

* | bottom of the screen,
    ** you see
+
[source]
----
--
Tests paused, press [r] to resume, [h] for more options>
----

    ** if you press `r` -> tests -- will -- start running -> bottom of the screen changes
+
[source]
----
--
Tests all passed, 2 tests were run, 0 were skipped. Tests took 1470ms.
Press [r] to re-run, [v] to view full results, [p] to pause, [h] for more options>
----

* ðŸ‘€if you want continuous testing to start AUTOMATICALLY -> set `quarkus.test.continuous-testing=enabled` | `application.properties`ðŸ‘€

== Controlling Continuous Testing

* | terminal / run `mvn quarkus:dev`
    ** `h` displays AVAILABLE commands

[source]
----
The following commands are available:
[r] - Re-run all tests
[f] - Re-run failed tests
[b] - Toggle 'broken only' mode, where only failing tests are run (disabled)
        # == enable / disable 'broken only' mode
        # 'broken only' mode    run ONLY failing tests
[v] - Print failures from the last test run
[p] - Pause tests
        # uses
        #   you make LOTS of changes & ONLY want feedback | ALL changes are done
[o] - Toggle test output (disabled)
        # enable / disable test output | console
        #   ALTHOUGH AVAILABLE | Dev UI's Continuous Testing section
[i] - Toggle instrumentation based reload (disabled)
        # enable / disable instrumentation based reload
        #   if enabled -> modify the clases | run time
        #   if disabled -> check PERIODICALLY the clases
[l] - Toggle live reload (enabled)
        # NOT directly related to testing
[s] - Force restart
        # force a scan + perform a live reload
[h] - Display this help
[q] - Quit
----

== Continuous Testing Without Dev Mode

* use cases
    ** avoid dev mode interfere with your tests
        *** _Example:_ running wiremock | same port
    ** develop using tests

* ways to run
    ** `mvn quarkus:test` OR
    ** `gradle quarkusTest`

== Selecting Tests to Run

* ways
    ** src/main/resources/application.properties
        *** âš ï¸ONLY valid | quarkus:dev âš ï¸
        *** `quarkus.test.include-pattern` OR (== exclusive, 1 OR ANOTHER one)
            **** âš ï¸if you configure it -> `exclude-pattern` is ignoredâš ï¸
            **** == ðŸ‘€regular expressionsðŸ‘€ / match -- against the -- test class' FULLY qualified class name
        *** `quarkus.test.exclude-pattern`
    ** build system
        *** 's priority > properties' priority
        *** | Maven,
            **** `-Dtest=\...` system property
        *** | Gradle,
            **** `--tests \...`

=== Maven

The `-Dtest=\...` system property selects given test(s) for continuous testing.
The format of this configuration property is the same as the Maven Surefire `-Dtest=\...` https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#test[format].
Specifically: it is a comma (`,`) separated list of globs of class file paths and/or method names.
Each glob can potentially be prefixed with an exclamation mark (`!`), which makes it an exclusion filter instead of an inclusion filter.
Exclusions have higher priority than inclusions.
The class file path glob is separated from the method name glob by the hash sign (`#`) and multiple method name globs may be present, separated by the plus sign (`+`).

For example:

* `Basic*`: all classes starting with `Basic`
* `???Test`: all classes named with 3 arbitrary characters followed by `Test`
* `!Unstable*`: all classes except classes starting with `Unstable`
* `pkg/**/Ci*leTest`: all classes in the package `pkg` and subpackages, starting with `Ci` and ending with `leTest`
* `*Test#test*One+testTwo?????`: all classes ending with `Test`, and in them, only methods starting with `test` and ending with `One`, or starting with `testTwo` and followed by 5 arbitrary characters
* `#fast*+slowTest`: all classes, and in them, only methods starting with `fast` or methods named `slowTest`

Note that the syntax `%regex[\...]` and `%ant[\...]` is _NOT_ supported.

=== Gradle

The `--tests \...` command line option selects given test(s) for continuous testing.
The format is the same as the `gradle test --tests \...` https://docs.gradle.org/current/userguide/java_testing.html#test_filtering[format].
Specifically: the option can be passed multiple times, and each item is a simple pattern for the test class name and optionally a method name.
When the pattern starts with an upper case letter, it matches a simple name of the class; otherwise, it matches a fully qualified name of the class.
After the class name, separated by a period (`.`), a method name pattern may be included.
The only wildcard character supported is `\*`, which matches an arbitrary number of characters.
Note that `*` is based purely on text, it doesn't pay extra attention to package delimiters.

For example:

* `com.example.Basic*`: all classes in package `com.example` starting with `Basic`
* `MyTest*`: all classes whose simple name starts with `MyTest`
* `\*.pkg.Test*`: all classes in package `pkg` (regardless of the parent packages) starting with `Test`
* `MyTest.test*`: all classes whose simple name is `MyTest`, and in them, only methods starting with `test`
* `com.example.IntegTest.fast*`: the class `com.example.IntegTest`, and in it, only methods starting with `fast`

== Multi-module Projects

Note that continuous testing supports multi-module projects, so tests in modules other than the application can still
be run when files are changed. The modules that are run can be controlled using config as listed below.

This is enabled by default, and can be disabled via `quarkus.test.only-test-application-module=true`.

== Configuring Continuous Testing

Continuous testing supports multiple configuration options that can be used to limit the tests that are run, and
to control the output. The configuration properties are shown below:

include::{generated-dir}/config/quarkus-core_quarkus.test.adoc[opts=optional, leveloffset=+2]

