////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Observability Dev Services
include::_attributes.adoc[]
:categories: observability,devservices,telemetry,metrics,tracing,logging
:summary: Entry point for Observability DevServices
:topics: observability,grafana,lgtm,prometheus,victoriametrics,jaeger,otel,otlp
:extensions: io.quarkus:quarkus-observability-devservices

* Observability
    ** requires orchestrate & connect > 1 Dev Service
        *** _Example:_
            **** metrics agent periodically scrape application for metrics / push them | timeseries database
            **** Grafana feeds graphs of this timeseries data

* Dev Resource
    ** == adapter between Dev Service concept & https://testcontainers.com/[Testcontainers]
    ** 's implementation == `@QuarkusTestResourceLifecycleManager` implementation
    ** ways to use
        *** Dev Services can pick-up various Dev Resources | classpath + apply xref:dev-services.adoc[Dev Service] concept
        *** explicitly disable Dev Services + enable Dev Resources + use starting and stopping Dev Resources' less-heavy concept
        *** explicitly disable Dev Services & Dev Resources + use Quarkus' `@QuarkusTestResource`

* ways
    ** add Observability extension dependency + Dev Resources dependencies, OR
    ** use existing `sinks`
        *** == pom.xml files / add
            **** Observability extension dependency
            **** other required dependencies / certain technology stacks
        *** _Example:_ `victoriametrics` sink == `quarkus-observability-devresource-victoriametrics` + `quarkus-victoriametrics-client` dependencies /
            **** ⚠️ `<scope>provided</scope>` ⚠️
                ***** Reason:🧠otherwise, some libraries (testcontainers) end up | your app's production libraries🧠
+
[source, xml]
----
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-observability-devservices-...</artifactId>
            <scope>provided</scope> <!-- !! -->
        </dependency>
----

* xref:observability-devservices-lgtm.adoc[Getting Started with Grafana-OTel-LGTM]
