////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Using OpenTelemetry Logging
include::_attributes.adoc[]
:extension-status: preview
:categories: observability
:summary: This guide explains how your Quarkus application can utilize OpenTelemetry Logging to provide distributed logging for interactive web applications.
:topics: observability,opentelemetry,logging
:extensions: io.quarkus:quarkus-opentelemetry

* goal
    ** how your web Quarkus application can provide -- , via https://opentelemetry.io/[OpenTelemetry] (OTel), -- distributed logging

* OpenTelemetry Logging
    ** ⚠️by default, disabled⚠️
        *** Reason:🧠_tech preview_🧠

include::{includes}/extension-status.adoc[]

include::{includes}/observability-include.adoc[]

== Prerequisites

:prerequisites-docker-compose:
include::{includes}/prerequisites.adoc[]

== Solution

* link:{quickstarts-tree-url}/opentelemetry-quickstart[here]

== Creating the Maven project

:create-app-artifact-id: opentelemetry-quickstart
:create-app-extensions: rest,quarkus-opentelemetry
include::{includes}/devtools/create-app.adoc[]

* `quarkus-opentelemetry` extension
    ** == default OpenTelemetry support + gRPC span exporter for https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md[OTLP]

:add-extension-extensions: opentelemetry
include::{includes}/devtools/extension-add.adoc[]

=== Examine the Jakarta REST resource

Create a `src/main/java/org/acme/opentelemetry/TracedResource.java` file with the following content:

[source,java]
----
package org.acme.opentelemetry;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.jboss.logging.Logger;

@Path("/hello")
public class TracedResource {

    private static final Logger LOG = Logger.getLogger(TracedResource.class);

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        LOG.info("hello");
        return "hello";
    }
}
----

If you have followed the tracing guide, this class will seem familiar. The main difference is that now, the `hello` message logged with `org.jboss.logging.Logger` will end up in the OpenTelemetry logs.

=== Create the configuration

[source,properties]
----
quarkus.otel.logs.enabled=true
----

To change any of the default property values, here is an example on how to configure the default OTLP gRPC Exporter within the application, using the `src/main/resources/application.properties` file:

[source,properties]
----
quarkus.application.name=myservice // <1>
quarkus.otel.logs.enabled=true // <2>
quarkus.otel.exporter.otlp.logs.endpoint=http://localhost:4317 // <3>
quarkus.otel.exporter.otlp.logs.headers=authorization=Bearer my_secret // <4>
----

<1> All logs created from the application will include an OpenTelemetry `Resource` indicating the logs were created by the `myservice` application.
If not set, it will default to the artifact id.
<2> Enable the OpenTelemetry logging.
Must be set at build time.
<3> gRPC endpoint to send the logs.
If not set, it will default to `http://localhost:4317`.
<4> Optional gRPC headers commonly used for authentication.

To configure the connection using the same properties for all signals, please check the base xref:opentelemetry.adoc#create-the-configuration[configuration section of the OpenTelemetry guide].

== Run the application

First we need to start a system to visualise the OpenTelemetry data.
We have 2 options:

* Start an all-in-one Grafana OTel LGTM system for traces, metrics and logs.

=== See the data

==== Grafana OTel LGTM option

* Take a look at: xref:observability-devservices-lgtm.adoc[Getting Started with Grafana-OTel-LGTM].

This features a Quarkus Dev service including a Grafana for visualizing data, Loki to store logs, Tempo to store traces and Prometheus to store metrics. Also provides and OTel collector to receive the data.

==== Logging exporter

You can output all logs to the console by setting the exporter to `logging` in the `application.properties` file:
[source, properties]
----
quarkus.otel.logs.exporter=logging <1>
----

<1> Set the exporter to `logging`.
Normally you don't need to set this.
The default is `cdi`.


Also add this dependency to your project:
[source,xml]
----
<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-exporter-logging</artifactId>
</dependency>
----

[[configuration-reference]]
== OpenTelemetry Configuration Reference

See the main xref:opentelemetry.adoc#configuration-reference[OpenTelemetry Guide configuration] reference.
