////
This guide is maintained in the main Quarkus repository
and pull requests should be submitted there:
https://github.com/quarkusio/quarkus/tree/main/docs/src/main/asciidoc
////
= Platform
include::_attributes.adoc[]
:categories: architecture
:summary: Learn more about what we call a Platform in the Quarkus world.
:topics: internals,platform

== Quarkus Platform

* https://github.com/dancer1325/quarkiverse/blob/main/docs/Home.md#quarkiverse-vs-quarkus-platform[definition]
* != ⚠️ https://github.com/dancer1325/quarkiverse/blob/main/docs/Home.md[Quarkiverse]⚠️

=== Quarkus Platform Artifacts

* recommendations
    ** FEW artifacts
    ** provide <<Quarkus Platform BOM,1 BOM>>

=== Quarkus Platform BOM

* ⚠️requirements⚠️
    ** imports a chosen version of `io.quarkus:quarkus-bom`
        *** OR flattened == import ALL individual BOM's dependencies != the BOM
    ** includes
        *** ALL Quarkus extension artifacts (runtime & deployment ones) / platform consists of
        *** ALL necessary third-party artifacts / compatible BETWEEN ALL platform extensions' transitive dependency versions
        *** <<platform-descriptor,platform JSON descriptor>> artifact
        *** POSSIBLY <<platform-properties,platform configuration properties>> artifacts

* uses
    ** 👀Quarkus applications / want to include extensions -- from a -- Quarkus platform -> import the Quarkus platform BOM👀

[[platform-descriptor]]
=== Quarkus Platform Descriptor

* Quarkus platform descriptor
    ** == JSON artifact /
        *** provides , -- to the -- Quarkus tools, information about
            **** platform
            **** its extensions
    ** uses
        *** add & remove extensions to/from the project on user's request, by
            **** https://code.quarkus.io/[Quarkus initializr]
            **** Quarkus command line tools
        *** as a Quarkus platform identifier

* TODO:
When Quarkus tools need to identify the Quarkus platform(s) used in the project,
they will analyze the dependency version constraints of the project
(the effective list of the managed dependencies from the `dependencyManagement` section in Maven terms)
looking for the platform descriptor artifact(s) among them

Given that the platform descriptors are included into the Quarkus platform BOMs,
every Quarkus application will inherit the platform descriptor artifact from the imported platform BOM(s)
as a dependency version constraint (managed dependency in Maven terms).

To be able to easily identify Quarkus platform descriptors among the project's dependency constraints, the platform descriptor Maven artifact coordinates should follow the following naming convention:

* the `groupId` of the descriptor artifact should match the `groupId` of the corresponding Quarkus Platform BOM;
* the `artifactId` of the descriptor artifact should be the `artifactId` of the corresponding Quarkus Platform BOM with the `-quarkus-platform-descriptor` suffix;
* the `classifier` of the descriptor artifact should match the `version` of the corresponding Quarkus Platform BOM;
* the `type` of the descriptor artifact should be `json`;
* the `version` of the descriptor artifact should match the `version` of the  corresponding Quarkus Platform BOM.

As a string it will look like `<platform-bom-groupId>:<platform-bom-artifactId>-quarkus-platform-descriptor:<platform-version>:json:<platform-version>`

E.g. the coordinates of the descriptor for the Quarkus BOM `{quarkus-platform-groupid}:quarkus-bom::pom:1.2.3` will be `{quarkus-platform-groupid}:quarkus-bom-quarkus-platform-descriptor:1.2.3:json:1.2.3`.
And for a custom Quarkus platform defined with BOM `org.acme:acme-bom::pom:555` it will be `org.acme:acme-bom-quarkus-platform-descriptor:555:json:555`.

The classifier matching the version of the platform may look confusing at first. But this is what turns the descriptor into a true "fingerprint" of the platform. In both Maven and Gradle, the effective set of the dependency version constraints (or the managed dependencies) is obtained by merging all the imported BOMs and version constraints specified individually in the current project and also its parent(s). The artifact `classifier` is a part of the dependency ID, which could be expressed as `groupId:artifactId:classifier:type`. Which means that if a project imports a couple of BOMs, e.g. `org.apple:apple-bom::pom:1.0` and `org.orange:orange-bom::pom:1.0`, and each of these two BOMs imports a different version `{quarkus-platform-groupid}:quarkus-bom::pom`, the Quarkus tools will be able to detect this fact and make the user aware of it, since it *might* not be a safe combination. If the descriptor artifact didn't include the classifier containing the version of the platform then the tools wouldn't be able to detect a potentially incompatible mix of different versions of the same platform in the same project.

The platform descriptor will normally be generated using a Maven plugin, e.g.

[source,xml]
----
<plugin>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-platform-descriptor-json-plugin</artifactId>
  <version>${quarkus.version}</version> <1>
  <executions>
    <execution>
      <phase>process-resources</phase>
      <goals>
        <goal>generate-extensions-json</goal> <2>
      </goals>
    </execution>
  </executions>
  <configuration>
    <bomGroupId>${quarkus.platform.group-id}</bomGroupId> <3>
    <bomArtifactId>${quarkus.platform.artifact-id}</bomArtifactId> <4>
    <bomVersion>${quarkus.platform.version}</bomVersion> <5>
    <overridesFile>${overridesfile}</overridesFile> <6>
    <resolveDependencyManagement>true</resolveDependencyManagement> <7>
  </configuration>
</plugin>
----

<1> the version of the `quarkus-platform-descriptor-json-plugin`
<2> `generate-extensions-json` is the goal generating the platform descriptor
<3> the `groupId` of the platform BOM
<4> the `artifactId` of the platform BOM
<5> the `version` of the platform BOM
<6> this parameter is optional, it allows to override some metadata from the Quarkus extension descriptors found in every runtime extension artifact from which the platform descriptor is generated
<7> this parameter is also optional and defaults to false. It has to be set to true in case the platform BOM *is not generated* and *is not flattened*. Which for example is the case for `io.quarkus:quarkus-bom`.

[[platform-properties]]
=== Quarkus Platform Properties -- "platform.properties" file --

* == another source of configuration
    ** hierarchy dominated -- by the -- application's `application.properties`
    ** loaded | `java.util.Properties` class's instance
    ** recommendations
       *** `platform.`
            **** naming

* uses
    ** provide Quarkus platform's configuration's default values
        *** ⚠️ONLY recommended CERTAIN configuration options⚠️

* Quarkus
    ** wires application configuration -- via -- https://github.com/smallrye/smallrye-config[SmallRye Config]
        *** link:config.adoc[MORE]

* 👀steps / BOM makes the platform's default properties available -- to -- ALL applications / use that platform👀
    ** create Quarkus Platform properties .xml
    ** | Quarkus Platform "pom.xml", add
+
[source,xml]
----
<dependency>
    <groupId>QuarkusPlatformBOMGroupIdValue</groupId>
    <artifactId>QuarkusPlatformBOMArtifactIdValue-quarkus-platform-properties</artifactId>
    <version>QuarkusPlatformBOMVersionValue</version>
    <type>properties</type>
<!--    <classifier>1.0.0</classifier>-->  <!-- empty OR null-->
</dependency>
----
* TODO:

Extension developers that want to make their configuration options platform-specific should set their default values to properties
that start with the `platform.` suffix. Here is an example:

[source,java]
----
package io.quarkus.deployment.pkg;

@ConfigRoot(phase = ConfigPhase.BUILD_TIME)
@ConfigMapping(prefix = "quarkus")
public interface NativeConfig {

    /**
     * The docker image to use to do the image build
     */
    @WithDefault("${platform.quarkus.native.builder-image}")
    String builderImage();
}
----

In this case the default value for `quarkus.native.builder-image` will be provided by the platform. The user will still be able to set the desired value for `quarkus.native.builder-image` in its `application.properties`, of course. But in case it's not customized by the user, the default value will be coming from the platform properties.
A platform properties file for the example above would contain:

[source,text,subs=attributes+]
----
platform.quarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:{mandrel-flavor}
----

[IMPORTANT]
====
Starting with Quarkus 3.19+, the _builder_ image used to build the native executable is based on UBI 9.
It means that the native executable produced by the container build will be based on UBI 9 as well.
So, if you plan to build a container, make sure that the base image in your `Dockerfile` is compatible with UBI 9.
The native executable will not run on UBI 8 base images.

For example to switch back to an UBI8 _builder image_ you can use:

`platform.quarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:{mandrel-flavor}`

You can see the available tags for UBI8 https://quay.io/repository/quarkus/ubi-quarkus-mandrel-builder-image?tab=tags[here]
and for UBI9 https://quay.io/repository/quarkus/ubi9-quarkus-mandrel-builder-image?tab=tags[here (UBI 9)])
====


There is also a Maven plugin goal that validates the platform properties content and its artifact coordinates and also checks whether the platform properties artifact is present in the platform's BOM
Here is a sample plugin configuration:

[source,xml]
----
<plugin>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-platform-descriptor-json-plugin</artifactId>
  <version>${quarkus.version}</version>
  <executions>
    <execution>
      <phase>process-resources</phase>
      <goals>
        <goal>platform-properties</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

==== Merging Quarkus Platform Properties

In case an application is importing more than one Quarkus platform and those platforms include their own platform properties artifacts, the content of those platform properties artifacts will be merged to form a single set of properties that will be used for the application build.
The order in which the properties artifacts are merged will correspond to the order in which they appear in the list of dependency version constraints of the application (in the Maven terms that will correspond to the effective list of application's managed dependencies, i.e. the flattened `managedDependencies` POM section).

IMPORTANT: The content of the properties artifacts found earlier will dominate over those found later among the application's dependency constraints!

That means if a platform needs to override a certain property value defined in the platform it is based on, it will need to include its platform properties artifact into the `managedDependencies` section of its BOM before importing the base platform.

For example, let's assume `org.acme:acme-quarkus-bom` platform extends the `io.quarkus:quarkus-bom` platform by importing its BOM. In case, the `org.acme:acme-quarkus-bom` platform were to override certain properties defined in the `io.quarkus:quarkus-bom-quarkus-platform-properties` included in the `io.quarkus:quarkus-bom`, the `org.acme:acme-quarkus-bom` would have to be composed as
[source,xml]
----
  <!-- skipped content -->

  <artifactId>acme-quarkus-bom</artifactId>
  <name>Acme - Quarkus - BOM</name>
  <packaging>pom</packaging>

  <dependencyManagement>
    <dependencies>
      <!-- Acme Quarkus platform properties -->
      <dependency>
        <groupId>org.acme</groupId>
        <artifactId>acme-quarkus-bom-quarkus-platform-properties</artifactId>
        <type>properties</type>
        <version>${project.version}</version>
      </dependency>

      <!-- The base Quarkus BOM -->
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-bom</artifactId>
        <version>${quarkus.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

  <!-- skipped content -->
----

That way, the `org.acme:acme-quarkus-bom` platform properties will appear before those provided by the `io.quarkus:quarkus-bom` properties and so will be dominating at build time.
